version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  lapin-blanc.cyrhades.fr:
    image: anssi/fcsc2023-hardware-lapin-blanc:latest
    read_only: true
    ports:
      - ${PORT_SSH}:4000